export const LabelsText = {
  task: {
    commentsLabel: $localize`:@@taskLabelComments:Comments`,
    addCommentsLabel: $localize`:@@taskLabelAddCommentsLabel:Add comments`,
    collaboratorsLabel: $localize`:@@taskLabelCollaborators:Collaborators`,
    completedBeforeLabel: $localize`:@@taskLabelCompletedBefore:Complete before`,
    completedTimeLabel: $localize`:@@taskLabelCompletedTime:On`,
    completedByLabel: $localize`:@@taskLabelCompletedBy:Completed by`,
    statusLabel: $localize`:@@taskLabelStatus:Status`,
    submitBtn: $localize`:@@taskLabelSubmitBtn:Save`,
    updateStatus: $localize`:@@taskLabelUpdateStatus:Update status`,
    updatedBy: $localize`:@@taskLabelUpdateBy:Last updated by`,
  },
  addTask: {
    titleSectionLabel: $localize`:@@addTaskLabelTitleSection:Add a task`,
    titleLabel: $localize`:@@addTaskLabelTitle:Title`,
    descriptionLabel: $localize`:@@addTaskLabelDescription:Description`,
    commentsLabel: $localize`:@@addTaskLabelComments:Comments`,
    completedExpectedDateLabel: $localize`:@@addTaskLabelCompletedExpectedTime:Complete before than`,
    completedStatDateLabel: $localize`:@@addTaskLabelCompletedStart:From: dd/mm/yyy`,
    completedEndDateLabel: $localize`:@@addTaskLabelCompletedEnd:To: dd/mm/yyy`,
    completedStatTimeLabel: $localize`:@@addTaskLabelCompletedStartTime:From`,
    completedEndTimeLabel: $localize`:@@addTaskLabelCompletedEndTime:To`,
    completedTimeLabel: $localize`:@@addTaskLabelCompletedTime:On`,
    completedByLabel: $localize`:@@addTaskLabelCompletedBy:Completed by`,
    collaboratorsEmail: $localize`:@@addTaskLabelCollaboratorsEmail:Collaborators' Email`,
    statusLabel: $localize`:@@addTaskLabelStatus:Status`,
    submitBtn: $localize`:@@addTaskLabelSubmitBtn:Save`,
    updateStatus: $localize`:@@addTaskLabelUpdateStatus:Update status`,
  },
  status: {
    completed: $localize`:@@statusCompleted:completed`,
    inProgress: $localize`:@@statusInProgress:in progress`,
    notCompleted: $localize`:@@statusNotCompleted:not completed`,
  },
  menu: {
    addTask: $localize`:@@menuAddTask:Add Task`,
    tasks: $localize`:@@menuTasks:Tasks`,
    title: $localize`:@@menuTitle:Tasks`,
    user: $localize`:@@menuUser:User`,
  },
  login: {
    actionsBtns: $localize`:@@loginActionBtns:or`,
    signUpBtn: $localize`:@@signInBtns:Sign up`,
    googleBtn: $localize`:@@loginGoogleBtn:Sign in with Google`,
    submitBtn: $localize`:@@loginSubmitBtn:Sign in`,
    placeholderUser: $localize`:@@loginUserInput:Enter your email`,
    placeholderPassword: $localize`:@@loginPasswordInput:Enter your password`,
    repeatderPassword: $localize`:@@loginPasswordInput:Repeat your password`,
  },
  signUp: {
    actionsBtns: $localize`:@@loginActionBtns:or`,
    signUpBtn: $localize`:@@signInBtns:Sign up`,
    googleBtn: $localize`:@@loginGoogleBtn:Sign up with Google`,
    loginBtn: $localize`:@@loginSubmitBtn:Login`,
    placeholderUser: $localize`:@@loginUserInput:Enter your email`,
    placeholderPassword: $localize`:@@loginPasswordInput:Enter your password`,
    repeatderPassword: $localize`:@@loginPasswordInput:Repeat your password`,
  },
  validators: {
    password: {
      repeat: $localize`:@@validatorsPasswordRepeat:Passwords are not the same`,
    }
  }
}
